### ISSUE TITLE
AttributeError: 'Vmf' object has no attribute 'hidden'

### ISSUE THREAD

**Issue by GEEKiDoS** [snake-biscuits/QtPyHammer#20]
Full log:
```
Traceback (most recent call last):
  File "D:\repo\QtPyHammer\QtPyHammer\ui\core.py", line 37, in open_files
    def open_files(): ops.open_files(self, self.map_browser)
  File "D:\repo\QtPyHammer\QtPyHammer\ops\__init__.py", line 38, in open_files
    main_window.open(filename)
  File "D:\repo\QtPyHammer\QtPyHammer\ui\core.py", line 313, in open
    tab = workspace.VmfTab(filename, new=False, parent=self)
  File "D:\repo\QtPyHammer\QtPyHammer\ui\workspace.py", line 38, in __init__
    self.map_file = VmfInterface(self, self.filename)
  File "D:\repo\QtPyHammer\QtPyHammer\ops\vmf.py", line 17, in __init__
    self.hidden = self._vmf.hidden
AttributeError: 'Vmf' object has no attribute 'hidden'
```
Python version
```
(venv) D:\repo\QtPyHammer>python --version
Python 3.9.2
```
Installed package
```
(venv) D:\repo\QtPyHammer>pip list
Package    Version
---------- -------
cx-Freeze  6.1
fgdtools   1.0.1
future     0.18.2
numpy      1.18.5
pip        20.2.3
PyOpenGL   3.1.5
pyparsing  2.4.7
PyQt5      5.15.3
PyQt5-Qt   5.15.2
PyQt5-sip  12.8.1
setuptools 49.2.1
vmf-tool   0.1.0
```

**Comment by snake-biscuits** [comment]
The current version of the repo isn't working because I've been updating vmf-tool, but I've run into some issues loading & saving hidden objects.

The latest release of QtPyHammer should still be stable, but until vmf_tool is updated you'll keep getting that error because support for hidden objects hasn't been added yet.
